### ISSUE TITLE
batch_test.TestBatch fails trying to clone a non-existent repo

### ISSUE THREAD

**Issue by murukeshm** [riptano/cassandra-dtest#1487]
While running dtests on 3.0.14, `batch_test.TestBatch` tests fails because they try to clone `github.com:apache/cassandra-2.1`. Either [that repo](https://github.com/apache/cassandra-2.1) doesn't exist, or it's private; in either case it can't be cloned. Output:

```
ERROR: logged_batch_compatibility_5_test (batch_test.TestBatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dtest/dtests/dtest.py", line 590, in tearDown
    if not self.allow_log_errors and self.check_logs_for_errors():
  File "/home/dtest/dtests/dtest.py", line 607, in check_logs_for_errors
    ['\n'.join(msg) for msg in node.grep_log_for_errors()]))
  File "/home/dtest/.local/lib/python2.7/site-packages/ccmlib/node.py", line 373, in grep_log_for_errors
    return self.grep_log_for_errors_from(seek_start=getattr(self, 'error_mark', 0))
  File "/home/dtest/.local/lib/python2.7/site-packages/ccmlib/node.py", line 376, in grep_log_for_errors_from
    with open(os.path.join(self.get_path(), 'logs', filename)) as f:
IOError: [Errno 2] No such file or directory: '/tmp/dtest-rpyY3I/test/node1/logs/system.log'
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /tmp/dtest-rpyY3I
dtest: DEBUG: Done setting configuration options:
{   'initial_token': None,
    'num_tokens': '256',
    'phi_convict_threshold': 5,
    'range_request_timeout_in_ms': 10000,
    'read_request_timeout_in_ms': 10000,
    'request_timeout_in_ms': 10000,
    'truncate_request_timeout_in_ms': 10000,
    'write_request_timeout_in_ms': 10000}
dtest: DEBUG: Testing with 1 node(s) at version 'github:apache/cassandra-2.1', 2 node(s) at current version
ccm: INFO: Cloning Cassandra...
repository: INFO: Cloning into bare repository '/home/dtest/.ccm/repository/_git_cache_apache'...

repository: INFO: Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

dtest: DEBUG: removing ccm cluster test at: /tmp/dtest-rpyY3I
dtest: DEBUG: clearing ssl stores from [/tmp/dtest-rpyY3I] directory
--------------------- >> end captured logging << ---------------------
```
These are skipped for versions > 3.0.x.

What's it trying to do here?

[The tests](https://github.com/riptano/cassandra-dtest/blob/72b181a2ad8c597396ec76c654ddb8b635c102dc/batch_test.py#L295) also mention `github.com/apache/cassandra-2.2`, which doesn't exist either.

**Comment by ptnapoleon** [comment]
Sorry for the trouble you're having. Neither of those tests specify `github.com/apache/X`. They specify the version string `github:apache/cassandra-2.1` which ccm is parsing to mean 

`github:` --> Clone from github, not the asf git repos
`apache/` --> Clone from the apache/cassandra repository (as opposed to say, my fork of C*)
`cassandra-2.1` --> Clone the branch cassandra-2.1.

Sorry for the confusion. This syntax is frustratingly close to the `git@github.com:apache/cassandra` for specifying a remote.

Your issue is either in your ability to clone the `cassandra-2.1` branch from https://github.com/apache/cassandra or in CCM managing to do that for you. If you think it's the latter, please open an issue on pcmanus/ccm (I can help you over there).

As far as the tests being skipped on versions > 3.0.x, that does look suspect. I think they should run on 3.X as well. I'll leave this issue open until that's resolved. Thanks for pointing that out!

**Comment by ptnapoleon** [comment]
As far as I can tell, those tests should also run on 3.x.

**Comment by murukeshm** [comment]
Yep, the problem was git trying to clone over git+SSH. That was fixed by forcing git to use HTTPS:

     git config --global url."https://github.com/".insteadOf git@github.com:
Since you want to keep the issue open for the skipping 3.0.x part, should I edit the issue/title to reflect that being the more important aspect?

**Comment by ptnapoleon** [comment]
No need. I've already opened #1488 to fix this.
